project_id = "gumkxjeahojrcaqnosyz"

[functions.fetch-google-sheets]
verify_jwt = true

[functions.send-2fa-code]
verify_jwt = true

[functions.verify-2fa-code]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = false

[functions.support-case-webhook]
verify_jwt = true

[functions.generate-monthly-statements]
verify_jwt = false

[functions.lookup-stand-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.verify-password-reset]
verify_jwt = false
