// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in customer's profile: stand number, email, and phone numbers used for 2FA.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("id, email, stand_number, phone_number, phone_number_2, full_name").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? null, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/get-my-statements.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_statements_default = defineTool2({
  name: "get_my_statements",
  title: "Get my monthly statements",
  description: "Return monthly statements for the signed-in customer's stand: month, opening balance, payments received, closing balance, and overdue status. Ordered newest first.",
  inputSchema: {
    limit: z.number().int().optional().describe("Maximum number of statements to return. Defaults to 24.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser2(ctx);
    const { data: profile, error: profileError } = await client.from("profiles").select("stand_number").eq("id", ctx.getUserId()).maybeSingle();
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    if (!profile?.stand_number) {
      return {
        content: [{ type: "text", text: "No stand number is linked to your account." }],
        structuredContent: { statements: [] }
      };
    }
    const cap = Math.min(Math.max(limit ?? 24, 1), 120);
    const { data, error } = await client.from("monthly_statements").select(
      "statement_month, opening_balance, payments_received, total_payments, closing_balance, is_overdue, days_overdue, generated_at"
    ).eq("stand_number", profile.stand_number).order("statement_month", { ascending: false }).limit(cap);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            { stand_number: profile.stand_number, statements: data ?? [] },
            null,
            2
          )
        }
      ],
      structuredContent: { stand_number: profile.stand_number, statements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gumkxjeahojrcaqnosyz";
var mcp_default = defineMcp({
  name: "standledger-mcp",
  title: "StandLedger Customer Portal",
  version: "0.1.0",
  instructions: "Tools for the StandLedger customer portal (Warwickshire Pvt Ltd / Lake City). Each caller acts as the signed-in customer; all reads are scoped to that customer's stand under RLS. Use `get_my_profile` to look up the caller's stand and contact details, and `get_my_statements` to fetch their monthly account statements.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_statements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
